BEGIN TRANSACTION;


CREATE TABLE IF NOT EXISTS drivers (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
latitude REAL NOT NULL,
longitude REAL NOT NULL,
rating REAL DEFAULT 5.0,
num_rides INTEGER DEFAULT 0
);


CREATE TABLE IF NOT EXISTS users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
phone TEXT
);


CREATE TABLE IF NOT EXISTS rides (
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
driver_id INTEGER,
pickup_lat REAL,
pickup_lng REAL,
drop_lat REAL,
drop_lng REAL,
distance_km REAL,
status TEXT DEFAULT 'requested',
timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);


COMMIT;
